// <auto-generated />
namespace DTS.HelpDesk.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addDescriminatorToUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addDescriminatorToUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201412161623175_addDescriminatorToUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
